# Exported from Render on 2024-07-14T01:16:45Z
services:
- type: web
  name: ToDo-app
  runtime: node
  repo: https://github.com/AhmetCelil/ToDo-app
  plan: free
  region: oregon
  buildCommand: yarn
  startCommand: yarn start
version: "1"
